### ISSUE TITLE
Highlight buffers/processes anywhere in the line

### ISSUE THREAD

**Issue by Stebalien** [akreisher/eshell-syntax-highlighting#13]
Currently, buffers/processes (starting with `#<`) are only supported after a redirect `>`. Otherwise, they're highlighted as a comment.

However, I have some eshell commands that take buffers as arguments (allowing for, e.g., `cat #<mybuffer> | grep foo`). Right now this looks like:

![screen-3](https://github.com/akreisher/eshell-syntax-highlighting/assets/310393/8e9ac6be-0536-4b38-810f-7eb06fff2f02)

But it's not actually a comment.

For context, the `cat` command is:

```elisp
(defun eshell/cat (&rest args)
  "Like cat(1) but with syntax highlighting."
  (dolist (thing (flatten-list args))
    (let ((data
           (cl-typecase thing
             (buffer
              (with-current-buffer thing
                (if (eshell-interactive-output-p)
                    (progn (font-lock-ensure) (buffer-string))
                  (buffer-substring-no-properties (point-min) (point-max)))))
             (string
              (with-temp-buffer
                (set-buffer-multibyte t)
                (insert-file-contents thing)
                (when (eshell-interactive-output-p)
                  (let ((buffer-file-name (expand-file-name thing)))
                    (set-auto-mode))
                  (font-lock-ensure))
                (buffer-string))))))
      (remove-text-properties 0 (length data) '(read-only nil) data)
      (eshell-print data))))
```

**Comment by akreisher** [comment]
Should be fixed here: https://github.com/akreisher/eshell-syntax-highlighting/commit/8bf0494ca71944b9d4bfb8ec3c93ea29d46bc2f9

Thanks for reporting!

**Comment by Stebalien** [comment]
Works great. Thanks!
