### ISSUE TITLE
Using `eshell-syntax-highlighting-highlight-elisp` breaks autocompletion

### ISSUE THREAD

**Issue by LemonBreezes** [akreisher/eshell-syntax-highlighting#14]
Hi. Using `eshell-syntax-highlighting-highlight-elisp` breaks Corfu, Company, and likely many other packages. I have linked this to a Doom Emacs PR here: https://github.com/doomemacs/doomemacs/pull/7529.

But basically, the way this syntax highlighting is implemented involves repeatedly deleting and re-inserting the Lisp expression but doing so causes a noticeable typing latency and breaks every package that uses markers or overlays to store state. In particular, this feature breaks `completion--in-region` so it basically breaks all incremental autocompletion in Eshell Elisp. Personally, I believe this is an unacceptable trade-off for getting Elisp syntax highlighting in Eshell and probably most users using this package have silently had their Elisp autocompletion broken without knowing as I did.

**Comment by aikrahguzar** [comment]
This is a solution using indirect buffers,
```
diff --git a/eshell-syntax-highlighting.el b/eshell-syntax-highlighting.el
index 7d06304..7cd4e82 100644
--- a/eshell-syntax-highlighting.el
+++ b/eshell-syntax-highlighting.el
@@ -167,25 +167,34 @@
            (t 'eshell-syntax-highlighting-default-face))))
     (add-face-text-property beg end face)))
 
+(defvar eshell-syntax-highlighting--indirect-lisp-buffer nil)
+
+(defun eshell-syntax-highlighting--indriect-buffer ()
+  (or
+   eshell-syntax-highlighting--indirect-lisp-buffer
+   (with-current-buffer
+       (setq-local eshell-syntax-highlighting--indirect-lisp-buffer
+                   (make-indirect-buffer
+                    (current-buffer)
+                    (generate-new-buffer-name
+                     (concat " " (buffer-name) "-eshell-indirect"))))
+     (setq-local delay-mode-hooks t)
+     (let ((change-major-mode-hook nil)
+           (after-change-major-mode-hook nil))
+       (emacs-lisp-mode))
+     (setq-local font-lock-dont-widen t)
+     (setq-local font-lock-support-mode nil))
+   comint--indirect-buffer))
+
 (defun eshell-syntax-highlighting--highlight-elisp (beg end)
   "Highlight Emacs Lisp in region (BEG, END) natively through a temp buffer."
-  (let* ((elisp-end (condition-case
-                        nil (scan-sexps beg 1)
-                      (scan-error end)))
-         (str (buffer-substring-no-properties beg elisp-end)))
-    (if (not eshell-syntax-highlighting-highlight-elisp)
-        (eshell-syntax-highlighting--highlight beg (point) 'default)
-      (goto-char beg)
-      (insert
-       (with-temp-buffer
-         (erase-buffer)
-         (insert str)
-         (delay-mode-hooks (emacs-lisp-mode))
-         (font-lock-default-function 'emacs-lisp-mode)
-         (font-lock-default-fontify-region (point-min) (point-max) nil)
-         (buffer-string)))
-      (delete-region (point) (+ (point) (length str))))
-    (goto-char elisp-end)))
+    (let ((elisp-end (condition-case nil
+                         (scan-sexps beg 1)
+                       (scan-error end))))
+      (with-current-buffer (eshell-syntax-highlighting--indriect-buffer)
+        (narrow-to-region beg elisp-end)
+        (font-lock-ensure beg elisp-end))
+      (goto-char elisp-end)))
 
 (defun eshell-syntax-highlighting--highlight-substitutions (beg end)
   "Find and highlight command substitutions in region (BEG, END)."
```
It is probably better to go the way of `comint-fontify-input-mode` and allow running a setup hook in the indirect buffer. E.g. I would like it to turn on `highlight-quoted-mode`.

**Comment by LemonBreezes** [comment]
> This is a solution using indirect buffers,
> ...

It doesn't let me convert this into a draft, but consider this PR on pause until I investigate your solution. Hopefully this can be fixed upstream in `eshell-syntax-highlighting` and without any changes here.

**Comment by aikrahguzar** [comment]
> It doesn't let me convert this into a draft, but consider this PR on pause until I investigate your solution. Hopefully this can be fixed upstream in `eshell-syntax-highlighting` and without any changes here.

This is an issue. You probably meant the pr on the doom repo?
