### ISSUE TITLE
Feature request: continue working in the presence of `font-lock` methods

### ISSUE THREAD

**Issue by hab25** [akreisher/eshell-syntax-highlighting#19]
See https://github.com/akreisher/eshell-syntax-highlighting/issues/7#issuecomment-822093355 . 

In my case, I use `nix-prettify-mode` (see https://github.com/NixOS/nix-mode/blob/719feb7868fb567ecfe5578f6119892c771ac5e5/nix-prettify-mode.el#L124C1-L157C50).

---

I investigated why eshell's built-in highlighting continues to work under the above by looking at `#'eshell/ls` and `em-prompt.el`, I concluded that this feature request can probably be satisfied by switching all calls like 
```elisp
(add-face-text-property start end face)
```

 to something like 
```elisp
(add-text-properties start end (list 'font-lock-face face))
``` 
. 

Note that IIUC the latter overrides instead of prepending like the former, so, adding to the latter some more code to implement such prepending on a per-character basis, perhaps by copying a lot of the code in `#'add-display-text-property`, would probably be better (i.e. it would work with other code more often). 

Also note that this switch would have the added benefit of disabling `eshell-syntax-highlighting`'s highlighting when the user turns off `font-lock-mode`; I expect that most of the time when a user disables `font-lock-mode`, they are doing so because they want to see the buffer with no highlighting at all, so this switch would be additionally helping that use-case.

**Comment by akreisher** [comment]
Hi, thanks for the tip to use `font-lock-face`. See #20 . I just had to add some logic to handle the separate fontification of emacs lisp code. 

I tried the example in `nix-prettify-mode` and it seems to work (shortening the nix path without disabling highlighting).
