### ISSUE TITLE
Feature request: make the highlighting of a previous input change appropriately when it is edited

### ISSUE THREAD

**Issue by hab25** [akreisher/eshell-syntax-highlighting#22]
This is useful when using the built-in `'em-smart` and when then built-in `eshell-remap-previous-input` is `t` (the default).

This would probably require changing `#'eshell-syntax-highlighting--enable-highlighting`, which currently only handles the buffer's last input.

Perhaps having previous inputs have their highlighting be updated only if point is within them, by using `#'eshell-point-within-input-p` could make this change easy and performant. While this would miss programatic edits (e.g. `#'insert`ing a string containing a newline), I expect this use-case is  rare enough to be disregarded right now.

**Comment by akreisher** [comment]
Hi, I merged in https://github.com/akreisher/eshell-syntax-highlighting/pull/23 which should take care of this use case. I adapted the logic from `eshell-point-within-input-p` to not depend on the `eshell-remap-previous-input` variable and to support older emacs.
