### ISSUE TITLE
Wrong face for cd directory commands

### ISSUE THREAD

**Issue by WhatDothLife** [akreisher/eshell-syntax-highlighting#6]
To cite the documentation of `eshell-syntax-highlighting-directory-face`:
"Face used for directory cd commands in an Eshell command."

Now, when I type cd, the directory afterwards is highlighted with `eshell-syntax-highlighting-file-arg-face`.

**Comment by akreisher** [comment]
I've updated the doctring for more clarity [here](https://github.com/akreisher/eshell-syntax-highlighting/commit/cf919ce7142d6ee4617d9c41925ba6676ee7d807).

`eshell-syntax-highlighting-directory-face` is used when a directory is in the command position and `eshell-cd-on-directory` is non-nil, e.g.

`~/Downloads` will be highlighted with `eshell-syntax-highlighting-directory-face`:
```
$ ~/Downloads 
```

This will highlight `cd` as a command and `~/Downloads` as an argument
```
$ cd ~/Downloads 
```
